require("lazy").setup({
  "tpope/vim-sleuth",
  "ThePrimeagen/vim-be-good",
  require("lazy/plugins/zen-mode"),
  require("lazy/plugins/gitsigns"),
  require("lazy/plugins/which-key"),
  require("lazy/plugins/telescope"),
  require("lazy/plugins/lspconfig"),
  require("lazy/plugins/conform"),
  require("lazy/plugins/cmp"),
  require("lazy/plugins/todo-comments"),
  require("lazy/plugins/treesitter"),
  require("lazy/plugins/lualine"),
  require("lazy/plugins/vim-tmux-navigator"),
  require("lazy/plugins/oil"),
  require("lazy/plugins/neo-tree"),
  require("lazy/plugins/orgmode"),
  -- require 'lazy.plugins.debug',
  -- require("lazy.plugins.indent_line"),
  -- require 'lazy.plugins.lint',
  -- require 'lazy.plugins.autopairs',
  require("lazy/plugins/gruvbox"),
})
